site_name: "Linguagem Potigol"
site_url: "https://potigol.github.io/docs"
site_description: "Documentação da Linguagem Potigol"
theme:
  name: material
  language: pt-BR
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
  font:
    text: Roboto
    code: Source Code Pro
  features:
    - navigation.tabs
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/potigol
    - icon: material/twitter
      link: https://twitter.com/potigol

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - tables
  - admonition
  - attr_list
  - md_in_html

nav:
  - Início: 
    - Potigol: index.md
    - Instalação: basico/instalacao.md
  - Referência:
    - Referência: index.md
    - Básico:
      - Primeiros Passos: basico/primeiros_passos.md
      - Entrada e Saída: basico/entrada_saida.md
      - Variáveis: basico/variaveis.md
      - Tipos Básicos: basico/tipos_basicos.md
      - Números e Textos: basico/numeros_textos/
      - Matemática: matematica.md
    - Estruturas:
      - Decisão: estruturas/decisao/
      - Repetição: estruturas/repeticao/
    - Funções: funcoes.md
    - Tipos Compostos:
      - Listas: listas.md
      - Tuplas: tuplas.md
      - Registros: registro.md
    - Programação Funcional: funcional
    - Orientação a Objetos: objetos
  - Instalação: basico/instalacao.md
  - Extras:
    - Jerimum: '../jerimum'
    - Beecrowd: '../beecrowd'

# theme:
#   features:
#     - navigation.footer

#     
# markdown_extensions:

#   - pymdownx.tasklist:
#       clickable_checkbox: true
#   - pymdownx.highlight:
#       use_pygments: true


#   - codehilite:
#       use_pygments: true
#       pygments_style: bw #material
#       linenums: true


