site_name: "Linguagem Potigol"
site_url: "https://potigol.github.io/docs"
site_description: "Documentação da Linguagem Potigol"
theme:
  name: material
  language: pt-BR
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
  font:
    text: Roboto
    code: Source Code Pro
  features:
    - navigation.tabs
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/potigol
    - icon: material/twitter
      link: https://twitter.com/potigol

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - tables
  - admonition
  - attr_list
  - md_in_html

nav:
  - Início: index.md
  - Referência:
 #   - Referência: basico/
    - Básico:
      - Entrada e Saída: basico/entrada_saida.md
      - Primeiros Passos: basico/primeiros_passos.md
      - Variáveis: basico/variaveis.md
      - Tipos Básicos: basico/tipos_basicos.md
      - Números: basico/numeros_textos/numeros.md
      - Textos: basico/numeros_textos/texto.md
      - Matemática: matematica/matematica.md
    - Estruturas:
      - Estruturas: estruturas/README.md
      - Decisão: 
        - Estruturas de Decisão: estruturas/decisao/README.md
        - Se: estruturas/decisao/se.md
        - Escolha: estruturas/decisao/escolha.md
      - Repetição: 
        - Estruturas de Repetição: estruturas/repeticao/README.md
        - Para: estruturas/repeticao/para.md
        - Enquanto: estruturas/repeticao/enquanto.md
    - Funções: funcoes/README.md
    - Tipos Compostos:
      - Tipos Compostos: tipos_compostos/README.md
      - Listas: tipos_compostos/listas.md
      - Tuplas: tipos_compostos/tuplas.md
      - Registros: tipos_compostos/registros.md
    - Programação Funcional: funcional/README.md
    - Orientação a Objetos: objetos/README.md
  - Instalação: instalacao.md
  - Extras: extras.md


# theme:
#   features:
#     - navigation.footer

#     
# markdown_extensions:

#   - pymdownx.tasklist:
#       clickable_checkbox: true
#   - pymdownx.highlight:
#       use_pygments: true


#   - codehilite:
#       use_pygments: true
#       pygments_style: bw #material
#       linenums: true


